// Parameters
const authorId = 'b6c5fecf-0ef4-4f98-878a-c9edd0881a42';
const totalRecords = 100;
const baseTitle = 'Sample Post Title';
const baseContent = 'Sample content for post';
const sqlLines = [];

// Function to generate a random date within the past year
function getRandomDate() {
    const now = new Date();
    const randomDays = Math.floor(Math.random() * 365);
    const randomDate = new Date(now);
    randomDate.setDate(now.getDate() - randomDays);
    return randomDate.toISOString().slice(0, 19).replace('T', ' ');
}

// Function to generate SQL
for (let i = 1; i <= totalRecords; i++) {
    const postId = `UUID()`; // UUID will be generated by the database
    const postTitle = `${baseTitle} ${i}`;
    const postContent = `${baseContent} ${i}.`;
    const postImageName = `image_${i}.jpg`;
    const createdAt = getRandomDate();
    const postViews = Math.floor(Math.random() * 10000);

    sqlLines.push(
        `INSERT INTO posts (post_id, post_title, post_content, post_image_url, post_image_name, author_id, created_at, post_views)\n` +
            `VALUES (${postId}, '${postTitle}', '${postContent}', NULL, '${postImageName}', '${authorId}', '${createdAt}', ${postViews});`,
    );
}

// Output the result
console.log(sqlLines.join('\n'));
